version: '3'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.fonzkart.in
    domainname: fonzkart.in
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - /data/mailserver/mail-data/:/var/mail/
      - /data/mailserver/mail-state/:/var/mail-state/
      - /data/mailserver/mail-logs/:/var/log/mail/
      - /data/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERRIDE_HOSTNAME=mail.fonzkart.in
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
